name: Build
on:
  push:
    branches: [master]
  workflow_dispatch: { }

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java environment
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        id: build
        run: mvn -B -U -DskipTests clean install

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags:
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: remcowesterhoud/tecktalk-gitops-resources
          token: ${{ secrets.RESOURCE_REPO }}

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Kustomize image tag
        run: |
          kustomize edit set image ${{ steps.meta.outputs.tags }}
          git config --global user.email "kustomize@bot.com"
          git config --global user.name "Kustomize bot"
          git add .
          git commit -m "Set image tag `${{ steps.meta.outputs.tags }}`"
          git push
          kustomize build